org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

version=1.2.0
maven_group=org.lolicode.moemusic.bilibili

plugin_api_version=2.2.0
# MoeMusic's no-api components should not be used in plugins. We reference it here *only* for setting version constraints.
moemusic_version=1.4.0
fabric_loader=0.19.5
forge_loader=1.18.2-40.3.12
# 3.0.13 is the last version that targets java 17
neoforged_loader=3.0.13

# Minecraft Mod Metadata (for Fabric, Forge, and NeoForge loaders)
mod_id=moemusic_bilibili_source
mod_name=MoeMusic - Bilibili Source
mod_description=Bilibili music source plugin and Minecraft mod for MoeMusic.
mod_author=KoishiMoe
mod_license=AGPL-3.0-or-later
fabric_entrypoint=org.lolicode.moemusic.bilibili.platform.FabricEntrypoint

